### ISSUE TITLE
Hi!, i also try to create npm card , but i getting issue about npm registry.

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [garimasingh128/garimasingh-NPM-card#1]
`
![Screenshot (6)](https://user-images.githubusercontent.com/33393692/99792635-62808c80-2b4d-11eb-8151-265d91705e5d.png)
`

npm notice
npm notice package: govind1530@1.0.1
npm notice === Tarball Contents ===
npm notice 2.8kB card.js
npm notice 355B  package.json
npm notice 104B  README.md
npm notice 74B   build.sh
npm notice === Tarball Details ===
npm notice name:          govind1530
npm notice version:       1.0.1
npm notice package size:  1.5 kB
npm notice unpacked size: 3.3 kB
npm notice shasum:        b65cbc75fd866fc12f17c31158be91c7d8fec2b3
npm notice integrity:     sha512-sroPh3GnEVtW1[...]9EZWL+YI5HxNQ==
npm notice total files:   4
npm notice
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/govind1530 - Not found
npm ERR! 404
npm ERR! 404  'govind1530@1.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-11-20T10_56_21_294Z-debug.log

already have an account in npm, can you tell me what step am I missing?

**Comment by garimasingh128** [comment]
- Firstly, remove the node modules, package.json files and publish packages from cloned repo
- Then, follow these steps:
```
npm set init.author.name "Your Name"
npm set init.author.email "you@example.com"
npm set init.author.url "http://yourblog.com"

npm adduser
```
- Then create a package.json and publish it:
```
cd /path/to/your-project
npm init

npm install -g pakmanager
# this shows you dependencies as you `require`d them
pakmanager deps
# now edit `package.json` and add any deps you forgot aboutt

npm publish ./
```

**Follow this https://gist.github.com/coolaj86/1318304/27bc153c639dbbb7dee17c16bf4d5108afe28b44 to know more about how to add user and publish to it.**

**Comment by thtRajasthaniGuy** [comment]
well thanks to its worked
